import LocaleSwitcher from "@/components/common/LocaleSwitcher/LocaleSwitcher";
import { ThemeSwitch } from "@/components/common/ThemeSwitch/ThemeSwitch";
import Login_Layout from "@/components/layouts/login_layout";
import { Metadata } from "next";
import { getTranslations } from "next-intl/server";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations("Login");
  return {
    title: t("signIn"),
    description: "Generated by create next app",
    // icons: '/images/black-cat.svg',
  };
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Login_Layout>{children}</Login_Layout>;
}
