import LocaleSwitcher from "@/components/common/LocaleSwitcher/LocaleSwitcher";
import { ThemeSwitch } from "@/components/common/ThemeSwitch/ThemeSwitch";
import { Metadata } from "next";
import { getTranslations } from "next-intl/server";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations("Login");
  return {
    title: t("signIn"),
    description: "Generated by create next app",
    // icons: '/images/black-cat.svg',
  };
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {children}

      <div className="fixed top-5 right-5">
        <LocaleSwitcher />
      </div>

      {/* tailwind ไม่มี right-15 นะ ใช้เป็นค่า custom หรือ right-16 แทน */}
      <div className="fixed top-5 right-16">
        <ThemeSwitch />
      </div>
    </div>
  );
}
